# This rule is not used by the project djld1 itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to webapp.djl.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: djld1
    app.kubernetes.io/managed-by: kustomize
  name: djld1-viewer-role
rules:
- apiGroups:
  - webapp.djl.com
  resources:
  - djld1s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.djl.com
  resources:
  - djld1s/status
  verbs:
  - get
